# Generated by Django 4.1.6 on 2023-02-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
