# Generated by Django 4.1.6 on 2023-02-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_users_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
