# Generated by Django 4.1.6 on 2023-02-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
