# Generated by Django 4.1.6 on 2023-02-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='name',
        ),
    ]
